# backend/app/report.py
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                 Table, TableStyle, HRFlowable)
from reportlab.lib.enums import TA_CENTER
from io import BytesIO
from datetime import datetime
from html import escape

def generate_pdf_report(result: dict, subject: str, user_email: str) -> bytes:
    """
    Generate a professional PDF report for an email analysis result.
    Returns raw PDF bytes — send as StreamingResponse.
    """
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=2*cm, rightMargin=2*cm,
                            topMargin=2*cm, bottomMargin=2*cm)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title", parent=styles["Title"],
                                  fontSize=18, textColor=colors.HexColor("#1e293b"),
                                  spaceAfter=6)
    h2_style = ParagraphStyle("H2", parent=styles["Heading2"],
                               fontSize=13, textColor=colors.HexColor("#334155"),
                               spaceBefore=14, spaceAfter=6)
    body_style = ParagraphStyle("Body", parent=styles["Normal"],
                                 fontSize=10, leading=14,
                                 textColor=colors.HexColor("#475569"))

    risk_colors = {
        "high":   colors.HexColor("#dc2626"),
        "medium": colors.HexColor("#d97706"),
        "low":    colors.HexColor("#16a34a"),
    }
    rl = result.get("risk_level","low")

    story = [
        Paragraph("Phishing Email Analysis Report", title_style),
        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")),
        Spacer(1, 0.3*cm),

        Paragraph(f"Generated: {datetime.now().strftime('%B %d, %Y %H:%M UTC')}", body_style),
        Paragraph(f"Analyst: {escape(user_email)}", body_style),
        Paragraph(f"Subject: {escape(subject or '(no subject)')}", body_style),
        Spacer(1, 0.4*cm),

        Paragraph("Analysis Summary", h2_style),
    ]

    summary_data = [
        ["Field", "Value"],
        ["Verdict",       result.get("prediction","").upper()],
        ["Confidence",    f"{result.get('confidence',0):.1f}%"],
        ["Risk Level",    rl.upper()],
        ["Risk Score",    f"{result.get('risk_score',0):.1f} / 100"],
        ["Flagged Words", str(len(result.get("flagged_keywords",[])))],
        ["Suspicious URLs", str(len(result.get("suspicious_urls",[])))],
    ]

    table = Table(summary_data, colWidths=[5*cm, 12*cm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1e293b")),
        ("TEXTCOLOR",  (0,0), (-1,0), colors.white),
        ("FONTSIZE",   (0,0), (-1,-1), 10),
        ("ROWBACKGROUNDS", (0,1), (-1,-1),
         [colors.HexColor("#f8fafc"), colors.HexColor("#f1f5f9")]),
        ("GRID", (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
        ("LEFTPADDING",  (0,0), (-1,-1), 8),
        ("RIGHTPADDING", (0,0), (-1,-1), 8),
        ("TOPPADDING",   (0,0), (-1,-1), 6),
        ("BOTTOMPADDING",(0,0), (-1,-1), 6),
        ("TEXTCOLOR", (1,1), (1,1), risk_colors.get(rl, colors.black)),
    ]))
    story.append(table)

    if result.get("flagged_keywords"):
        story.append(Paragraph("Flagged Keywords", h2_style))
        kw_text = "  |  ".join(escape(str(keyword)) for keyword in result["flagged_keywords"])
        story.append(Paragraph(kw_text, body_style))

    if result.get("suspicious_urls"):
        story.append(Paragraph("Suspicious URLs", h2_style))
        url_data = [["URL", "Risk Score"]]
        for u in result["suspicious_urls"]:
            display_url = u["url"][:60] + "..." if len(u["url"]) > 60 else u["url"]
            url_data.append([escape(display_url),
                             str(u["score"])])
        url_table = Table(url_data, colWidths=[13*cm, 4*cm])
        url_table.setStyle(TableStyle([
            ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#7f1d1d")),
            ("TEXTCOLOR", (0,0),(-1,0),colors.white),
            ("FONTSIZE",  (0,0),(-1,-1),9),
            ("GRID",(0,0),(-1,-1),0.5,colors.HexColor("#fca5a5")),
            ("LEFTPADDING",(0,0),(-1,-1),6),
            ("TOPPADDING", (0,0),(-1,-1),5),
        ]))
        story.append(url_table)

    story.append(Spacer(1, 1*cm))
    story.append(HRFlowable(width="100%", thickness=0.5,
                             color=colors.HexColor("#e2e8f0")))
    story.append(Paragraph(
        "Generated by PhishGuard AI • For internal security use only",
        ParagraphStyle("footer", parent=styles["Normal"],
                       fontSize=8, textColor=colors.HexColor("#94a3b8"),
                       alignment=TA_CENTER)
    ))

    doc.build(story)
    return buf.getvalue()
